Repository CS3219-AY2223S1/cs3219-project-ay2223s1-g21, pull requests merged in 2022-11, with the labels that each got.

#143 [Ui] Css bugs for chatbox and match found!
  .gitignore
  compile-service/controller/compile-controller.js
  frontend/package.json
  frontend/src/pages/CollaborationPage/chat.css
  frontend/src/pages/CollaborationPage/index.js
  frontend/src/pages/Matching/MatchingScreen.js
  frontend/src/pages/Matching/matching.scss
Labels: bug

#149 [User service] Revert cookie for HTTPS
  frontend/src/components/Navbar/index.js
  frontend/src/components/ProfileSection/index.js
  frontend/src/components/Sidebar/index.js
  frontend/src/pages/CollaborationPage/index.js
  frontend/src/pages/LoginPage/index.js
  frontend/src/pages/Matching/Matching.js
  frontend/src/redux/actions/auth.js
  frontend/src/services/user_service.js
  user-service/controller/user-controller.js
  user-service/index.js
  user-service/package-lock.json
  user-service/package.json
  user-service/tests/test.js
Labels: high

#152 [User service] Fix HTTPS cross-site cookie
  user-service/index.js
Labels: high

#154 [Collab Service] Fix bug and add JWT token verification
  collab-service/controller/index.js
  collab-service/index.js
  collab-service/package-lock.json
  collab-service/package.json
  collab-service/utilities/authJwt.js
  frontend/src/pages/CollaborationPage/index.js
Labels: bug, enhancement

#157 [Ui] add link to history
  frontend/src/components/ProfileSection/History.js
Labels: bug, high

#158 [Ui] add duck logo
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo512.png
  frontend/src/pages/CollaborationPage/store.js
  twilio/index.js
  twilio/package-lock.json
  twilio/package.json
Labels: medium

#160 [Collab Service] Collaborative editing to fallback on socket io
  collab-service/index.js
  frontend/build/asset-manifest.json
  frontend/build/index.html
  frontend/build/static/js/main.6ce3aefc.js
  frontend/build/static/js/main.6ce3aefc.js.LICENSE.txt
  frontend/build/static/js/main.924a80dc.js
  frontend/build/static/js/main.924a80dc.js.LICENSE.txt
  frontend/src/pages/CollaborationPage/EmbeddedEditor/index.js
  frontend/src/pages/CollaborationPage/index.js
  frontend/src/redux/actionTypes.js
  frontend/src/redux/actions/collab.js
  frontend/src/redux/reducers/collab.js
  matching-service/controllers/MatchingController.js
  matching-service/models/Match.js
Labels: high
