Repository CS3219-AY2223S1/cs3219-project-ay2223s1-g21, pull requests merged in 2022-10, with the labels that each got.

#87 [Question service] Add link to question
  question-service/model/question-model.js
Labels: high

#89 [History] Add history APIs
  user-service/controller/user-controller.js
  user-service/index.js
  user-service/model/user-model.js
  user-service/model/user-orm.js
  user-service/model/user-repository.js
Labels: high

#91 [Question service] getQuestion query parameter
  question-service/controller/question-controller.js
Labels: high

#94 Implement random question fetch in collab pg
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.js
  frontend/src/pages/CollaborationPage/CollabElements.js
  frontend/src/pages/CollaborationPage/Description/Data.js
  frontend/src/pages/CollaborationPage/Description/index.js
  frontend/src/pages/CollaborationPage/EmbeddedEditor/EmbeddedElements.js
  frontend/src/pages/CollaborationPage/EmbeddedEditor/index.js
  frontend/src/pages/CollaborationPage/index.js
  frontend/src/pages/Matching/Matching.js
  frontend/src/redux/actionTypes.js
  frontend/src/redux/actions/collab.js
  frontend/src/redux/reducers/collab.js
  frontend/src/redux/reducers/index.js
  frontend/src/services/user_service.js
  user-service/package.json
Labels: high

#98 Add compiler support in FE
  compile-service/controller/compile-controller.js
  compile-service/controller/compileRequest.js
  compile-service/index.js
  compile-service/package-lock.json
  compile-service/package.json
  frontend/src/pages/CollaborationPage/CollabElements.js
  frontend/src/pages/CollaborationPage/Description/index.js
  frontend/src/pages/CollaborationPage/EmbeddedEditor/EmbeddedElements.js
  frontend/src/pages/CollaborationPage/EmbeddedEditor/index.js
  frontend/src/pages/CollaborationPage/QuestionSection/index.js
  frontend/src/pages/CollaborationPage/Result/ResultElements.js
  frontend/src/pages/CollaborationPage/Result/index.js
  frontend/src/pages/CollaborationPage/chat.css
  frontend/src/pages/CollaborationPage/index.js
  frontend/src/redux/actionTypes.js
  frontend/src/redux/actions/collab.js
  frontend/src/redux/reducers/collab.js
  frontend/src/services/compile_service.js
  frontend/src/services/question_service.js
  frontend/src/services/user_service.js
Labels: high

#100 [User service] Add cookie maxAge
  user-service/index.js
Labels: high

#117 [User service] Case-insensitive username
  user-service/controller/user-controller.js
Labels: high

#120 [User service] Update refresh token
  user-service/model/refreshToken-model.js
  user-service/model/refreshToken-orm.js
  user-service/model/refreshToken-repository.js
  user-service/package-lock.json
  user-service/package.json
Labels: high

#101 [Collab Service]
  collab-service/index.js
  collab-service/model/roomModel.js
  collab-service/package-lock.json
  collab-service/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/PrivateRoute/index.js
  frontend/src/pages/CollaborationPage/EmbeddedEditor/index.js
  frontend/src/pages/CollaborationPage/index.js
  frontend/src/pages/CollaborationPage/store.js
  frontend/src/pages/LoginPage/index.js
  frontend/src/pages/Matching/Matching.js
  frontend/src/pages/Matching/styles.js
  frontend/src/redux/actionTypes.js
  frontend/src/redux/reducers/matching.js
  matching-service/controllers/MatchingController.js
  matching-service/server.js
Labels: high

#122 [Ui] Refactor matching ui code
  frontend/src/pages/CollaborationPage/EmbeddedEditor/index.js
  frontend/src/pages/CollaborationPage/index.js
  frontend/src/pages/Matching/Matching.js
  frontend/src/redux/actionTypes.js
  frontend/src/redux/actions/collab.js
  frontend/src/redux/reducers/collab.js
  package.json
Labels: medium

#126 [Question service] Add optional id exclusion for getQuestion API
  question-service/controller/question-controller.js
  question-service/model/question-orm.js
  question-service/model/question-repository.js
Labels: high

#124 [Collab Service & Matching Service] Sync question between user in room and match cancel changes
  frontend/src/components/MainSection/index.js
  frontend/src/pages/CollaborationPage/Description/Data.js
  frontend/src/pages/CollaborationPage/Description/index.js
  frontend/src/pages/CollaborationPage/index.js
  frontend/src/pages/Matching/Matching.js
  frontend/src/redux/actionTypes.js
  frontend/src/redux/actions/collab.js
  frontend/src/redux/actions/matching.js
  frontend/src/redux/reducers/collab.js
  frontend/src/redux/reducers/matching.js
  frontend/src/services/question_service.js
  matching-service/controllers/MatchingController.js
  matching-service/server.js
Labels: enhancement

#131 [Ui] Integrate History feature
  frontend/src/components/FAQ/Data.js
  frontend/src/components/ProfileSection/History.js
  frontend/src/components/ProfileSection/ProfileElements.js
  frontend/src/components/ProfileSection/history.css
  frontend/src/components/ProfileSection/index.js
  frontend/src/components/TransitionButton.js
  frontend/src/components/TransitionButton.module.css
  frontend/src/pages/CollaborationPage/Description/index.js
  frontend/src/pages/CollaborationPage/index.js
  frontend/src/pages/CollaborationPage/store.js
  frontend/src/pages/LoginPage/index.js
  frontend/src/pages/LoginPage/signup.module.css
  frontend/src/pages/Matching/Matching.js
  frontend/src/redux/actionTypes.js
  frontend/src/redux/actions/collab.js
  frontend/src/redux/reducers/collab.js
  frontend/src/services/user_service.js
  user-service/controller/user-controller.js
  user-service/middleware/authJwt.js
Labels: high

#134 [Matching & Collab Service] Support next question feature
  collab-service/controller/index.js
  collab-service/index.js
  collab-service/model/roomModel.js
  collab-service/package-lock.json
  collab-service/package.json
  frontend/src/pages/CollaborationPage/Description/index.js
  frontend/src/pages/CollaborationPage/QuestionSection/index.js
  frontend/src/pages/CollaborationPage/index.js
  frontend/src/pages/Matching/Matching.js
  frontend/src/redux/actions/collab.js
  frontend/src/redux/actions/matching.js
  frontend/src/redux/reducers/collab.js
  frontend/src/redux/reducers/matching.js
  frontend/src/services/collab_service.js
  matching-service/controllers/MatchingController.js
  matching-service/server.js
  package-lock.json
  package.json
  question-service/controller/question-controller.js
Labels: high

#136 [User service] Revamp cookie in backend and frontend
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/LoginPage/index.js
  frontend/src/services/user_service.js
  question-service/controller/question-controller.js
  user-service/controller/user-controller.js
  user-service/index.js
  user-service/package-lock.json
  user-service/package.json
Labels: high

#138 [Ui] Fix logout button
  frontend/src/components/Navbar/index.js
  frontend/src/components/ProfileSection/History.js
  frontend/src/components/ProfileSection/ProfileElements.js
  frontend/src/components/ProfileSection/index.js
  frontend/src/components/Sidebar/index.js
  frontend/src/pages/CollaborationPage/index.js
  frontend/src/pages/Matching/Matching.js
  frontend/src/redux/actions/auth.js
  frontend/src/services/user_service.js
  user-service/controller/user-controller.js
  user-service/index.js
  user-service/tests/test.js
Labels: bug

#141 [Ui] Sync editor language between frontend instances
  frontend/src/components/Navbar/NavbarElements.js
  frontend/src/pages/CollaborationPage/EmbeddedEditor/index.js
  frontend/src/pages/CollaborationPage/index.js
  frontend/src/redux/actions/collab.js
  frontend/src/redux/reducers/collab.js
Labels: high
