Repository CS3219-AY2223S1/cs3219-project-ay2223s1-g21, pull requests merged in 2022-09, with the labels that each got.

#40 [Ui] Create a Ui to support application functionalities.
  .gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/assets/aboutImage.jpg
  frontend/src/assets/dancing-duck.gif
  frontend/src/components/AboutSection/AboutElements.js
  frontend/src/components/AboutSection/Data.js
  frontend/src/components/AboutSection/index.js
  frontend/src/components/ButtonElement.js
  frontend/src/components/FAQ/Data.js
  frontend/src/components/FAQ/FAQElements.js
  frontend/src/components/FAQ/index.js
  frontend/src/components/MainSection/MainElements.js
  frontend/src/components/MainSection/index.js
  frontend/src/components/Navbar/NavbarElements.js
  frontend/src/components/Navbar/index.js
  frontend/src/components/Sidebar/SidebarElements.js
  frontend/src/components/Sidebar/index.js
  frontend/src/constants.js
  frontend/src/index.js
  frontend/src/pages/ChangePasswordPage/changePasswordElements.js
  frontend/src/pages/ChangePasswordPage/index.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/LoadingScreen/index.js
  frontend/src/pages/LoginPage/backup.js
  frontend/src/pages/LoginPage/constants.js
  frontend/src/pages/LoginPage/index.js
  frontend/src/pages/LoginPage/signup.module.css
  frontend/src/pages/SignupPage/SignupPage.js
  frontend/src/pages/SignupPage/signup.module.css
  frontend/src/pages/backup.js
  frontend/src/redux/actionTypes.js
  frontend/src/redux/actions/auth.js
  frontend/src/redux/reducers/auth.js
  frontend/src/redux/reducers/index.js
  frontend/src/redux/store.js
  frontend/src/services/user_service.js
Labels: high

#44 Add hash refresh, token verification, strict password criteria
  user-service/controller/user-controller.js
  user-service/index.js
  user-service/middleware/authJwt.js
  user-service/model/refreshToken-model.js
  user-service/model/refreshToken-orm.js
  user-service/model/refreshToken-repository.js
  user-service/model/user-orm.js
  user-service/util/constants.js
  user-service/util/password-regex.js
Labels: high

#45 [Ui] Implement silent login feature
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Navbar/index.js
  frontend/src/components/PrivateRoute/index.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/LoginPage/index.js
  frontend/src/pages/LoginPage/silentLogin.js
  frontend/src/redux/actionTypes.js
  frontend/src/redux/actions/auth.js
  frontend/src/redux/reducers/auth.js
  frontend/src/services/user_service.js
  user-service/controller/user-controller.js
  user-service/index.js
Labels: high

#46 [User FR7] Reset password
  user-service/controller/user-controller.js
  user-service/index.js
  user-service/model/passwordToken-model.js
  user-service/model/passwordToken-orm.js
  user-service/model/passwordToken-repository.js
  user-service/model/refreshToken-model.js
  user-service/model/user-model.js
  user-service/model/user-orm.js
  user-service/package-lock.json
  user-service/package.json
  user-service/util/email/requestResetPassword.handlebars
  user-service/util/email/resetPassword.handlebars
  user-service/util/email/sendEmail.js
Labels: high

#48 [Ui] Change password
  frontend/src/App.js
  frontend/src/assets/leftArrow.png
  frontend/src/assets/profile.png
  frontend/src/components/MainSection/index.js
  frontend/src/components/Navbar/index.js
  frontend/src/components/PrivateRoute/index.js
  frontend/src/components/ProfileSection/ProfileElements.js
  frontend/src/components/ProfileSection/index.js
  frontend/src/components/Sidebar/index.js
  frontend/src/pages/ChangePasswordPage/changePasswordElements.js
  frontend/src/pages/ChangePasswordPage/index.js
  frontend/src/pages/LoginPage/index.js
  frontend/src/pages/LoginPage/silentLogin.js
  frontend/src/pages/Profile/index.js
  frontend/src/services/user_service.js
  user-service/controller/user-controller.js
Labels: high

#50 [USER] Debug requestPasswordReset API
  user-service/controller/user-controller.js
  user-service/util/email/requestResetPassword.handlebars
Labels: bug, high

#54 [User] Add Web MVC – SPA architecture orm methods
  user-service/controller/user-controller.js
  user-service/model/passwordToken-orm.js
  user-service/model/user-orm.js
Labels: high

#56 [User] Update HTTP methods
  user-service/index.js
Labels: high

#26 [MS] Matching service implementation
  .gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/MainSection/index.js
  frontend/src/configs.js
  frontend/src/pages/Matching/Matching.js
  frontend/src/pages/Matching/matching.module.css
  frontend/src/pages/Matching/styles.js
  frontend/src/pages/layout/Page.js
  frontend/src/pages/layout/page.module.css
  frontend/src/redux/actionTypes.js
  frontend/src/redux/actions/auth.js
  frontend/src/redux/actions/matching.js
  frontend/src/redux/reducers/auth.js
  frontend/src/redux/reducers/index.js
  frontend/src/redux/reducers/matching.js
  matching-service/controllers/MatchingController.js
  matching-service/index.js
  matching-service/models/Interview.js
  matching-service/models/Match.js
  matching-service/package-lock.json
  matching-service/package.json
  matching-service/routes.js
  matching-service/server.js
  matching-service/utilities/auth/authJwt.js
  matching-service/utilities/constants/Difficulty.js
  matching-service/utilities/constants/LogMessages.js
  matching-service/utilities/constants/ResponseStatus.js
  matching-service/utilities/errors/ClientError.js
  matching-service/utilities/errors/MongoError.js
  matching-service/utilities/helpers/HelperFunctions.js
  package-lock.json
  package.json
Labels: high

#61 [User] Integration tests
  package.json
  user-service/controller/user-controller.js
  user-service/index.js
  user-service/package-lock.json
  user-service/package.json
  user-service/tests/test.js
Labels: high

#63 [Ui] Update client http methods
  frontend/src/components/MainSection/index.js
  frontend/src/components/ProfileSection/index.js
  frontend/src/pages/Matching/Matching.js
  frontend/src/pages/PasswordReset/index.js
  frontend/src/services/user_service.js
  user-service/model/passwordToken-orm.js
Labels: medium

#72 [Collab Ui] Create collaboration page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/assets/homeScreenBgm.mp3
  frontend/src/components/FAQ/index.js
  frontend/src/components/InnerHtmlAdder/index.js
  frontend/src/components/MainSection/index.js
  frontend/src/components/Navbar/index.js
  frontend/src/pages/CollaborationPage/CollabElements.js
  frontend/src/pages/CollaborationPage/Data.js
  frontend/src/pages/CollaborationPage/Description.js
  frontend/src/pages/CollaborationPage/DescriptionElements.js
  frontend/src/pages/CollaborationPage/EmbeddedEditor.js
  frontend/src/pages/CollaborationPage/EmbeddedElements.js
  frontend/src/pages/CollaborationPage/QuestionSection.js
  frontend/src/pages/CollaborationPage/QuestionSectionElements.js
  frontend/src/pages/CollaborationPage/Submissions.js
  frontend/src/pages/CollaborationPage/index.js
  frontend/src/pages/CollaborationPage/markup.css
  frontend/src/pages/Home/index.js
Labels: high

#76 [Collab Ui] add resizer and difficulty tag
  frontend/src/pages/CollaborationPage/Chatbox/index.js
  frontend/src/pages/CollaborationPage/CollabElements.js
  frontend/src/pages/CollaborationPage/Description/DescriptionElements.js
  frontend/src/pages/CollaborationPage/Description/index.js
  frontend/src/pages/CollaborationPage/Description/markup.css
  frontend/src/pages/CollaborationPage/EmbeddedEditor.js
  frontend/src/pages/CollaborationPage/EmbeddedEditor/Data.js
  frontend/src/pages/CollaborationPage/EmbeddedEditor/EmbeddedElements.js
  frontend/src/pages/CollaborationPage/EmbeddedEditor/index.js
  frontend/src/pages/CollaborationPage/QuestionSection/QuestionSectionElements.js
  frontend/src/pages/CollaborationPage/QuestionSection/index.js
  frontend/src/pages/CollaborationPage/index.js
Labels: high

#81 [Question] Add question-service
  frontend/src/pages/CollaborationPage/Description/DescriptionElements.js
  frontend/src/pages/CollaborationPage/Description/index.js
  frontend/src/pages/CollaborationPage/EmbeddedEditor/Data.js
  question-service/controller/question-controller.js
  question-service/index.js
  question-service/model/question-model.js
  question-service/model/question-orm.js
  question-service/model/question-repository.js
  question-service/package-lock.json
  question-service/package.json
  question-service/util/constants.js
Labels: high
